CLI preproc
czbiohub/dynamorph pull request #20
Opened 2021-02-18 00:41 UTC by bryantChhun

Introduce a CLI for preprocessing steps.

This PR also enables preprocessing of single-page tiff datasets.  It sorts and then filters z-slices based on string parsing.

This is tested on the small dataset here:
`/gpfs/CompMicro/projects/dynamorph/microglia/subset_for_tests/mg_small/JUNE/tiffs`
and the output written here:
`/gpfs/CompMicro/projects/dynamorph/microglia/subset_for_tests/mg_small/JUNE/tiffs`

Resulting "composite" .npy arrays are 3-channels with Phase, Retardance, BF in channels index position 0, 1, 2, respectively.

2021-02-25 00:50 UTC, smguo requested changes

2021-02-25 00:50 UTC, smguo commented on configs/config_example.yml
> +  fov: ['C5-Site_0','C5-Site_1']
What would be the value for `fov` if the user wants to process all fovs? Maybe add docstrings?

2021-02-25 00:50 UTC, smguo commented on configs/config_example.yml
> +  z_slice: 2
Does `z_slice` take a list of z indices? Maybe consider rename as `z_index`?

2021-02-25 00:50 UTC, smguo commented on pipeline/preprocess.py
> +             z_slice: int = 2):
How about change to list to support 5D data?

2021-02-25 00:50 UTC, smguo commented on pipeline/preprocess.py
> +    fullpath = os.path.join(path, site)
Here the data are assumed to have file structure path/site/file, but reconstruct-order also has an option to output  path/file as position is already embedded in the file name ( ...p###z###.tif). Can we add this support in the next PR if not this one?

2021-02-25 00:50 UTC, smguo commented on pipeline/preprocess.py
> +                     z_slice: int,
Maybe add docstrings for new inputs?

2021-03-02 21:02 UTC, bryantChhun commented on configs/config_example.yml
> +  fov: ['C5-Site_0','C5-Site_1']
here FOV does a hard subfile-walk.  I should add handling for all fovs or none.

2021-03-02 21:24 UTC, smguo commented on configs/config_example.yml
> +  fov: ['C5-Site_0','C5-Site_1']
I added handling for all fovs in #21. Handling for multiple z-slices is yet not added

2021-03-02 22:27 UTC, bryantChhun commented on configs/config_example.yml
> +  z_slice: 2
let's address this in PR #21

2021-03-02 22:28 UTC, bryantChhun commented on configs/config_example.yml
> +  fov: ['C5-Site_0','C5-Site_1']
(i'll add docstrings here)

2021-03-03 02:51 UTC, bryantChhun commented on pipeline/preprocess.py
> +             z_slice: int = 2):
ok, i think i can do this here.  Will need to stack the pages differently then.

2021-03-05 06:46 UTC, miaecle commented
Everything looks fine to me. I guess the change really depends on the actual use case scenario, right now this preprocessing pipeline assumes inputs are all from 1 z-slice (I guess phase will always be 1 slice), maybe we could think about if to include multiple z-slices in the data loading pipeline.

2021-03-10 00:41 UTC, bryantChhun commented on pipeline/preprocess.py
> +    fullpath = os.path.join(path, site)
support for flat data structured added in this PR.  Now there is a config file flag that asks "pos_dir" = True if each position is in a directory

2021-03-10 00:50 UTC, merged